-- MySQL Script generated by MySQL Workbench
-- Fri Mar 22 13:36:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema pruebalinktic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pruebalinktic` ;

-- -----------------------------------------------------
-- Schema pruebalinktic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pruebalinktic` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `pruebalinktic` ;

-- -----------------------------------------------------
-- Table `pruebalinktic`.`amparo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebalinktic`.`amparo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pruebalinktic`.`amparo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `codigo_amparos` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `valor_prima` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `UK_p2wuf6438uwwstp9yt6dm3q4n` ON `pruebalinktic`.`amparo` (`codigo_amparos` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pruebalinktic`.`asegurado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebalinktic`.`asegurado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pruebalinktic`.`asegurado` (
  `numero_identificacion` INT NOT NULL,
  `tipo_identificacion_id` INT NULL DEFAULT NULL,
  `valor_asegurado` INT NULL DEFAULT NULL,
  `genero_id` BIGINT NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(255) NOT NULL,
  `fecha_nacimiento` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `UK_hy7958efk66tfy397w5mibl0s` ON `pruebalinktic`.`asegurado` (`numero_identificacion` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FKa73lps8djnlbm2sx2ksn3gpy4` ON `pruebalinktic`.`asegurado` (`genero_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FK81or59uhhfh9usmqbo154wo4r` ON `pruebalinktic`.`asegurado` (`tipo_identificacion_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pruebalinktic`.`genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebalinktic`.`genero` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pruebalinktic`.`genero` (
  `codigo` INT NULL DEFAULT NULL,
  `id` BIGINT NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pruebalinktic`.`liquidacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebalinktic`.`liquidacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pruebalinktic`.`liquidacion` (
  `asegurado_id` BIGINT NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `prima_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `FKo3i8lqyqthd83ynprl1ame6n0` ON `pruebalinktic`.`liquidacion` (`asegurado_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FKpfe3yq566cf49lwc2ygl7lehq` ON `pruebalinktic`.`liquidacion` (`prima_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pruebalinktic`.`prima`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebalinktic`.`prima` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pruebalinktic`.`prima` (
  `codigo_prima` INT NOT NULL,
  `edad_maxima` INT NOT NULL,
  `edad_minima` INT NOT NULL,
  `porcentaje_prima` DOUBLE NOT NULL,
  `amparo_id` BIGINT NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `FKb6l9pjphwssvj36d7l520apds` ON `pruebalinktic`.`prima` (`amparo_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pruebalinktic`.`tipo_identificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebalinktic`.`tipo_identificacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pruebalinktic`.`tipo_identificacion` (
  `codigo` INT NULL DEFAULT NULL,
  `id` INT NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      